# Generated by Django 2.2.20 on 2021-07-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swamps', '0003_surveydata_surveysite'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveydata',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swamps.SurveySite'),
        ),
    ]
