# Generated by Django 2.2.20 on 2021-07-18 06:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swamps', '0004_surveydata_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysite',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=32756),
        ),
    ]
