# Generated by Django 2.2.20 on 2021-09-30 13:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swamps', '0006_auto_20210719_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysite',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32756),
        )
    ]
