# Generated by Django 2.2.20 on 2021-10-05 05:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swamps', '0008_surveysite_swamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysite',
            name='activities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='SurveyData',
        ),
    ]
